### ISSUE TITLE
Usage/wiki

### ISSUE THREAD

**Issue by kesumin** [prplwtf/blueprint-redirect#1]
## Feature Request
I'm having trouble figuring out how to use this extension. I have no clue where to start either. 
Could you please update the readme or let me know how to operate the extension? I can submit the pr as well myself to update the readme. 

Thank you

**Comment by prplwtf** [comment]
I'll look into making a explanation of how to use Redirect and what it exactly does. I'll leave this issue open until that's sorted.

**Comment by FunkFrog** [comment]
I just wanted to chime in with an explanation of how to use the plugin after looking through the source code, for @kesumin and anyone else looking in the meantime!

- Your redirect URL will be mywebsite.com/\<the redirect name\>, e.g. mywebsite.com/test for a redirect named simply "test"

- You need to modify your NGINX or apache configuration, whatever you're using, to make sure your index page is set to read both index.php (for pterodactyl) _as well as_ index.html (for the redirect), otherwise the redirect URL will just give you a 403. 

For example, in NGINX, within the ssh server block, the line
`index index.php;`
needs to be changed to
`index index.php index.html;`
Then restart NGINX with the command `sudo systemctl restart nginx`

Then, once you add a redirect via the redirect panel, you should be able to visit the url corresponding to your redirect name!

@prplwtf, if you'd like me to open a pull request to modify the README, I'd be happy to re-write this in a more detailed and well written way for you! Thanks for the plugin!

**Comment by prplwtf** [comment]
Thanks for the explanation! Feel free to open a pull request.

**Comment by FunkFrog** [comment]
I've opened #2 with changes to the README!

**Comment by prplwtf** [comment]
> I've opened #2 with changes to the README!

Looks good! I've merged it.

**Comment by FunkFrog** [comment]
Awesome, thanks!
